# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'quiz', ((b'Q', b'Question'), (b'S', b'Solution'))), (b'U', b'Unknown')], max_length=1)),
                ('image', models.ImageField(default=b'anonymous.jpg', upload_to=b'uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'anonymous', max_length=20)),
                ('number_of_options', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphQl.category')),
                ('correct_option', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphQl.option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphQl.question'),
        ),
    ]
