# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphQl', '0003_auto_20171015_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default=b'anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default=b'anonymous'),
        ),
    ]
